### ISSUE TITLE
"Quotes are ridiculously huge"

### ISSUE THREAD

**Issue by davelab6** [EbenSorkin/Merriweather#57]
<img width="484" alt="screen shot 2017-11-08 at 13 17 22" src="https://user-images.githubusercontent.com/261579/32574854-30a40028-c487-11e7-8271-6c0de164e333.png">

https://twitter.com/jessiemihalik/status/915237926249869312

**Comment by jmihalik** [comment]
Yeah, so that twit above is mine. Sorry! I couldn't find anything I liked better than Merriweather, so I ended up downloading the glyph files and modifying the quotes slightly. You can see the result on www.jessiemihalik.com or in the attached screenshot. I realize this is personal preference, so feel free to close the issue if you prefer the quotes as-is. :)
![fonts](https://user-images.githubusercontent.com/713307/32576514-ccb9625e-c49c-11e7-8a27-7c781b3c606b.png)

**Comment by EbenSorkin** [comment]
I agree with high-rez screen becoming ever more common toning down the quotes size and length was needed. That is now done. I'll be interested to see if you feel the new ones are good.

**Comment by kauesena** [comment]
Hi. Sorry to post on an old closed issue. I am one that really liked the long quotes. I have recently seen that the variable Merriweather became available via google fonts, so I have started using it. I soon noticed that something was off and it was indeed the small quotes and commas. I think they fit in really well with the big `!` and `?`. Would it be possible to add the original design back as a stylistic set?

**Comment by EbenSorkin** [comment]
Yeah. I could do that. I’m looking at trying to get Arabic script support
in and Greek next but it may be possible to get a set of smaller updates
pushed including this before then. I don’t control how fast updates are
made public. But I can post a build to github. Would that work or do you
need it as part of the service?

**Comment by kauesena** [comment]
Posting it to GitHub would be excellent, thank you! While it wouldn’t cover all my use cases, knowing it will eventually reach Google Fonts is already great.

It’s exciting to hear that you’ll soon be working on Greek support. [I’m particularly interested in seeing Merriweather eventually gain an OpenType Math version—I [posted](https://github.com/SorkinType/Merriweather/issues/543) about it some time ago. Having Greek support is a big step in that direction. If you ever consider working towards that, I’d be happy to help with math characters, as they should be simpler to design than an alphabet. I only have access to FontForge (on Linux), though, and if I remember correctly, Merriweather’s source files are for a MacOS-specific software.]

**Comment by kauesena** [comment]
As I have mentioned only `“ ”` having the original long design as alternates, I would like to explicitly mention the basic quotation marks also, `"` and `'`. They are now slanted, which may be good in an apostrophe function, but is inconvenient when it should enclose a segment of text as a symmetrical pair. It would therefore be nice to have the original vertical design as an alternate too.

Thank you again for willingness to post a new build, and for all your work on this great font. Please let me know if I should restate all the things here in a new issue in the current repository. (I noticed after posting that not only is this a very old issue, but is in the retired repository.)

**Comment by EbenSorkin** [comment]
I may be able to make some strides with straight quotes and curly quotes
this during this upcoming week. Greek will take a bit longer 😹.

**Comment by kauesena** [comment]
Hey @EbenSorkin ! Just pinging in the hope that you may have some time to generate that build as I have stumbled upon this aesthetic question again. (I mean the build with the option to use the old big quotation marks and commas (and moreover vertical in the case of ' ").)

**Comment by EbenSorkin** [comment]
I made some progress with Greek but have another project for Google that will end around Sept 1. After that I can add the quotes feature. Would an OpenType stylistic set be the ideal way to do this for you? Like ss01? I am planning improvements to kerning. I am not sure what's involved in making OpenType Math work but I'll make inquiries in Sept.

**Comment by kauesena** [comment]
Very nice to know you have been able to make progress with Greek. After Greek letters are added, Merriweather may someday be the best font for math websites and ebooks. (I'd be happy to contribute with math symbols as their design is simpler than that of letters. I only have access to Fontforge though.)

I think alternate stylistic sets would be ideal, because people seem to prefer the more inconspicuous versions of the characters. But being able to download a version with that set as default for local use would be very useful too. (Many, like myself, must find the previous larger design more readable — specially for complexly structured and heavily punctuated text where one needs to keep track of the different voices in direct speech and citations within paragraphs, e.g. reports, papers, news articles, bibliographic reviews, study notes, novels etc.)

**Comment by EbenSorkin** [comment]
I have a lot of questions. Are there Math fonts whose glyphs sets seem like
particularly excellent references? How do math fonts vary in quality? Where
do they tend to fail or frustrate? What would be a big win? What counts as
particularly satisfying? Are any of the best math fonts Libre/on Google
fonts?

-e.
